# Generated by Django 4.1.5 on 2023-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_score_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2048)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('date_valid', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
