# Generated by Django 4.1.5 on 2023-01-12 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_announcement_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('downloadable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_valid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
