# Generated by Django 4.1.5 on 2023-01-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_download_alter_announcement_date_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='posted',
            field=models.DateField(auto_now=True),
        ),
    ]
