# Generated by Django 4.1.5 on 2023-01-12 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_announcement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
